### ISSUE TITLE
Execution with single quote (') does not work.  Only recognizes double (")

### ISSUE THREAD

**Issue by adamvi** [hafen/atom-r-exec#10]
When trying to execute a line of code from Atom to Mac terminal (Shift+CMD+T) the following code works:

     devtools::install_github("adamvi/SGP")

while this does not:

     devtools::install_github('adamvi/SGP')

Exchangeable usage of single and double quotes would be most appreciated!

**Comment by pimentel** [comment]
Fixed in my fork: https://github.com/pimentel/atom-r-exec

Will be making a pull request in the next few days

**Comment by pimentel** [comment]
This has been resolved and I think should be close now?
