### ISSUE TITLE
iTerm

### ISSUE THREAD

**Issue by rpietro** [hafen/atom-r-exec#11]
Hi, fantastic package. I was trying to get my scripts sent over to iTerm, but couldn't get it to work. Any thoughts?

**Comment by funkhou9** [comment]
+1

**Comment by pimentel** [comment]
I just added support in my own fork: https://github.com/pimentel/atom-r-exec

I will add documentation in my pull request hopefully by the end of this week.

**Comment by rpietro** [comment]
new version seems to work now
