### ISSUE TITLE
New version & sending setwd every time

### ISSUE THREAD

**Issue by franvillamil** [hafen/atom-r-exec#15]
Hi,

I was trying to avoid sending the working directory every time some code is sent to the R console, and I saw that in the new version (0.3.0) there's an option for that, besides some other changes. Yet, I couldn't install or update the new version, is there any way to do that? And in case it is not, where could I find the line of code to change the ```setwd``` feature?

By the way, thanks a lot for this package!!

**Comment by pimentel** [comment]
@franvillamil what issues are you having installing? are there any error messages you can provide?

After you get it installed, you can go to the settings page for the package (Settings => r-exec) and you will see that there are key bindings for changing the working directory. The default is: `cmd-shift-e`

**Comment by hafen** [comment]
Sorry, I had forgotten to `apm publish` @pimentel's great work.  v0.3.0 should be available to install through the standard install interface now.

**Comment by franvillamil** [comment]
I just got the notification of updates available in Atom, and it works perfect. Thanks a lot!!

**Comment by pimentel** [comment]
It sounds like this has been resolved and should be closed now?

**Comment by hafen** [comment]
Yes thanks - I'm a bit behind.
